### ISSUE TITLE
Process scans cannot handle Nonetype (when there aren't any scans to process)

### ISSUE THREAD

**Issue by pritchyspritch** [alphagov/cyber-security-nessus#60]
```
Processing scans and sending to cloudwatch...
listing scans
for scan in scans
Traceback (most recent call last):
File "process_scans.py", line 112, in <module>
main(None, None)
File "process_scans.py", line 108, in main
find_scans()
File "process_scans.py", line 17, in find_scans
for scan in scans["scans"]:
TypeError: 'NoneType' object is not iterable
```

**Comment by akinnane** [comment]
I see it fails when there are no scans available but the end result is the same - no scans are sent to cloudtrail.

**Comment by pritchyspritch** [comment]
Fixed by https://github.com/alphagov/cyber-security-nessus/pull/62
